name: Deploy DLT Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Databricks CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/v0.259.0/install.sh | sh
        echo "/usr/local/bin" >> $GITHUB_PATH

    - name: Check Databricks CLI version
      run: databricks --version

    - name: Configure Databricks CLI for AAD
      env:
        DATABRICKS_HOST:          ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_CLIENT_ID:     ${{ secrets.DATABRICKS_CLIENT_ID }}
        DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
        DATABRICKS_AZURE_TENANT_ID: ${{ secrets.DATABRICKS_TENANT_ID }}
      run: |
        # non‑interactive AAD login writes ~/.databrickscfg
        databricks configure --aad <<EOF
        $DATABRICKS_HOST
        $DATABRICKS_CLIENT_ID
        $DATABRICKS_CLIENT_SECRET
        $DATABRICKS_AZURE_TENANT_ID
        EOF

    - name: Deploy pipeline
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
        DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
        DATABRICKS_AZURE_TENANT_ID: ${{ secrets.DATABRICKS_TENANT_ID }}
        # DATABRICKS_CONFIG_PROFILE: ${{ secrets.DATABRICKS_CONFIG_PROFILE }}
      run: |
        databricks bundle validate 
        databricks bundle deploy -t prod
        databricks bundle run -t prod gdelt_wiki_dlt
      # Validates and deploys the pipeline using Databricks Asset Bundle