name: Deploy DLT Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Databricks CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/v0.259.0/install.sh | sh
        echo "/usr/local/bin" >> $GITHUB_PATH

    - name: Check Databricks CLI version
      run: databricks --version

      
    - name: Configure Databricks CLI
      run: |
        echo "[DEFAULT]" > ~/.databrickscfg
        echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
        echo "client_id = $DATABRICKS_CLIENT_ID" >> ~/.databrickscfg
        echo "client_secret = $DATABRICKS_CLIENT_SECRET" >> ~/.databrickscfg
        echo "azure_tenant_id = $DATABRICKS_TENANT_ID" >> ~/.databrickscfg
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
        DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
        DATABRICKS_TENANT_ID: ${{ secrets.DATABRICKS_TENANT_ID }}

    - name: Deploy pipeline
      run: |
        databricks bundle validate --profile DEFAULT
        databricks bundle deploy --profile DEFAULT
      # Validates and deploys the pipeline using Databricks Asset Bundle