name: Deply DLT Pipeline

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Databricks CLI
      run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/v0.259.0/install.sh | sudo sh

    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
        DATABRICKS_TENANT_ID: ${{ secrets.DATABRICKS_TENANT_ID }}
        DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
      run: |
        databricks configure --aad-token
    
    - name: Deploy pipeline
      run: |
        # databricks pipelines create --json-file dlt_pipeline_config.json \
        #   || databricks pipelines update --json-file dlt_pipeline_config.json

        databricks bundle validate --profile adb-4336080139557394
        databricks bundle deploy --profile adb-4336080139557394
        